version: '3.8'
services:
  mercedes-app:
    image: mercedes-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercedes-app
    restart: unless-stopped
    ports:
      - "8080:8080"