version: '3.8'
services:
  recruitment-app:
    image: recruitment-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-app
    restart: unless-stopped
    ports:
      - "8080:8080"