### Create a shortened URL
POST http://localhost:8080/api/shorten
Content-Type: application/json

{
  "id": "test1",
  "longUrl": "test1",
  "ttl": 3600
}

### Read long URL (redirect)
GET http://localhost:8080/api/test1

### Delete the shortened URL
DELETE http://localhost:8080/api/customId
